server:
  port: 9030
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  format: TEXT
  level:
    org:
      springframework:
        data:
          r2dbc: ERROR
spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/pica
    pool:
      max-size: 15
      max-idle-time: 10m
      validation-query: SELECT 1
    username: root
    password: admin1234
    name: pica

  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    producer:
      client-id: sds-identity-provider
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    jaas:
      enabled: true
